name: get_cali_data_x3
model_type: TDQuantModel
scale: 3
num_gpu: 1
manual_seed: 0
gpu: 0
cali_data_save_path: keydata/cali_data_x3.pth

# dataset and data loader settings
datasets:
  train:
    task: SR
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: datasets/DF2K/HR
    dataroot_lq: datasets/DF2K/LR_bicubic/X3
    filename_tmpl: "{}x3"
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: True
    use_rot: True

    # data loader
    use_shuffle: True
    num_worker_per_gpu: 0
    batch_size_per_gpu: 32
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    task: SR
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/benchmark/Set5/HR
    dataroot_lq: datasets/benchmark/Set5/LR_bicubic/X3
    filename_tmpl: "{}x3"
    io_backend:
      type: disk

train:
  total_iter: 3000
  warmup_iter: -1 # no warm up



# paths
path:
  pretrain_network_FP: experiments/pretrained_models/SwinIR/002_lightweightSR_DIV2K_s64w8_SwinIR-S_x2.pth
  strict_load_FP: true

# logging settings
logger:
  print_freq: 10
  save_checkpoint_freq: !!float 5e2
  use_tb_logger: False
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
